---
title: Sawyer's
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: 
url: http://example.com
twitter_username: jekyllrb
github_username: jekyll
phone: "(860) 618-5411"
address: "79 Center St\x03<br/>\nTorrington, CT <br/>\n06790"
